---
- name: Install dependencies and configure environment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install essential packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - wget
        - git
        - gcc
        - g++
        - libffi-dev
        - htop
        - xclip
        - make
        - vim
        - python3-dev
        - python3-pip
        - python3-venv
        - libpq-dev
        - libsqlite3-dev
        - lzma-dev
        - libreadline6-dev
        - libbz2-dev
        - cargo
        - bash
        - zsh
        - neofetch
        - unzip
        - ripgrep

    - name: Install additional packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - fd-find
        - bat

    - name: Install lsd
      apt:
        deb: "https://github.com/lsd-rs/lsd/releases/download/v1.0.0/lsd-musl_1.0.0_amd64.deb"
        state: present

    - name: Create symlinks for fd and bat
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop:
        - { src: "{{ ansible_playbook_dir }}/.local/bin/fd", dest: "~/.local/bin/fd" }
        - { src: "{{ ansible_playbook_dir }}/.local/bin/bat", dest: "~/.local/bin/bat" }

    - name: Install pyenv
      shell: "curl https://pyenv.run | bash"

    - name: Install Node.js using fnm
      shell: "curl -fsSL https://fnm.vercel.app/install | bash && /bin/zsh -i -c 'fnm install 16'"

    - name: Install fzf
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.fzf
        version: master
      become: yes

    - name: Run fzf install script
      command: "~/.fzf/install --all"

    - name: Install Neovim, omb, and oh-my-zsh
      shell: "./.cfg/scripts/install-neovim.sh && ./.cfg/scripts/install-omb.sh && ./.cfg/scripts/install-omz.sh"

    - name: Install Starship prompt
      shell: "sh -c 'curl -fsSL https://starship.rs/install.sh | bash -s -- -f'"

    - name: Install pipx and packages
      pipx:
        package: "{{ item }}"
      loop:
        - ansible
        - git+https://github.com/politeauthority/docker-pretty-ps.git#egg=docker-pretty-ps
        - ranger-fm
        - poetry
        - ipython
      become: yes

    - name: Copy configuration files
      copy:
        src: "{{ item }}"
        dest: "~"
      loop:
        - .bashrc
        - .zshrc

- name: Set default shell
  hosts: localhost
  tasks:
    - name: Set default shell to zsh
      shell: chsh -s /bin/zsh "{{ ansible_ssh_user }}"
