---
- name: Install dependencies and configure environment
  hosts: localhost
  become: false
  gather_facts: true
  tasks:
    - name: Update apt cache (Ubuntu)
      become: true
      apt:
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install essential packages (Ubuntu)
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - wget
        - git
        - gcc
        - g++
        - libffi-dev
        - htop
        - xclip
        - make
        - vim
        - python3-dev
        - python3-pip
        - python3-venv
        - libpq-dev
        - libsqlite3-dev
        - lzma-dev
        - libreadline6-dev
        - libbz2-dev
        - bash
        - zsh
        - neofetch
        - unzip
        - ripgrep
        - bat
        - fd-find
      when: ansible_os_family == 'Debian'

    - name: Update Homebrew (macOS)
      become: true
      homebrew:
        state: latest
      when: ansible_os_family == 'Darwin'

    - name: Install essential packages (macOS)
      homebrew:
        name: "{{ item }}"
      loop:
        - curl
        - wget
        - git
        - gcc
        - libffi
        - htop
        - xclip
        - make
        - vim
        - python
        - postgresql
        - sqlite
        - xz
        - readline
        - bzip2
        - bash
        - zsh
        - neofetch
        - unzip
        - ripgrep
        - bat
        - fd
      when: ansible_os_family == 'Darwin'

    - name: Create symlink for fd
      become: true
      shell: ln -sf "$(which fdfind)" /usr/bin/fd
      args:
        creates: "/usr/bin/fd"
      when: ansible_os_family == 'Debian'

    - name: Create symlink for bat
      become: true
      shell: ln -sf "$(which batcat)" /usr/bin/bat
      args:
        creates: "/usr/bin/bat"
      when: ansible_os_family == 'Debian'

- hosts: localhost
  name: Set up bash
  tasks:
    - name: Install Oh My Bash
      shell: |
        . ~/.bashrc
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
      args:
        executable: /bin/bash

    - name: Move backup files to .bashrc
      shell: mv -f ~/.bashrc.omb* ~/.bashrc
      args:
        executable: /bin/bash

- name: Set default shell
  hosts: localhost
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Set default shell to zsh
      shell: chsh -s /bin/zsh "{{ the_user }}"
